[build]
base = ""                        
command = "npm run build --prefix vite-template"
publish = "vite-template/dist"
functions = "functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
